import type { Metadata } from 'next'
import { CssBaseline } from '@mui/material'
import { ThemeProvider } from "@mui/material/styles";

import Header from './components/layout/header'
import { theme } from './theme'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>

          <ThemeProvider theme={theme}>
            <CssBaseline />
            <Header />
            {children}
          </ThemeProvider>
      </body>
    </html>
  )
}
